import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { ClerkProvider } from '@clerk/nextjs'
import ConvexClientProvider from '@/components/convex-client-provider'
import AppInit from "@/components/app-init";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "ApexLRP",
    description: "Generated by create next app",
};

function RootLayoutContent({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <ConvexClientProvider>
                <AppInit />
                <LanguageProvider>
                    {children}
                </LanguageProvider>
            </ConvexClientProvider>
        </ClerkProvider>
    );
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <RootLayoutContent>{children}</RootLayoutContent>
            </body>
        </html>
    );
}
