import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { LanguageToggle } from "@/components/language-toggle";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "ApexLRP",
    description: "Generated by create next app",
};

function RootLayoutContent({ children }: { children: React.ReactNode }) {
    return (
        <LanguageProvider>
            <Navbar />
            {/* Language Toggle - Fixed in top right corner */}
            <div className="fixed top-6 right-6 z-50">
                <LanguageToggle />
            </div>
            {children}
        </LanguageProvider>
    );
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <RootLayoutContent>{children}</RootLayoutContent>
            </body>
        </html>
    );
}
